#! /bin/bash
setfacl -m u:www-data:--- /usr/bin/curl
setfacl -m u:www-data:--- /bin/rm
setfacl -m u:www-data:--- /bin/echo
setfacl -m u:www-data:--- /bin/mv
setfacl -m u:www-data:--- /usr/bin/tail
setfacl -m u:www-data:--- /usr/bin/head
setfacl -m u:www-data:--- /usr/bin/git
setfacl -m u:www-data:--- /usr/bin/wget
setfacl -m u:www-data:--- /usr/bin/locate
setfacl -m u:www-data:--- /usr/bin/find
setfacl -m u:www-data:--- /usr/bin/apt
setfacl -m u:www-data:--- /usr/bin/scp
setfacl -m u:www-data:--- /usr/local/bin/pip
setfacl -m u:www-data:--- /usr/bin/nl
setfacl -m u:www-data:--- /sbin/ip
setfacl -m u:www-data:--- /bin/hostname
setfacl -m u:www-data:--- /bin/rmdir
setfacl -m u:www-data:--- /usr/bin/dpkg
setfacl -m u:www-data:--- /bin/cat
setfacl -m u:www-data:--- /usr/bin/setfacl
setfacl -m u:www-data:--- /usr/bin/apt-get
setfacl -m u:www-data:--- /usr/bin/unlink
setfacl -m u:www-data:--- /bin/cp
setfacl -m u:champion:--- /usr/bin/curl
setfacl -m u:champion:--- /bin/rm
setfacl -m u:champion:--- /bin/echo
setfacl -m u:champion:--- /bin/mv
setfacl -m u:champion:--- /usr/bin/tail
setfacl -m u:champion:--- /usr/bin/head
setfacl -m u:champion:--- /usr/bin/git
setfacl -m u:champion:--- /usr/bin/wget
setfacl -m u:champion:--- /usr/bin/locate
setfacl -m u:champion:--- /usr/bin/find
setfacl -m u:champion:--- /usr/bin/apt
setfacl -m u:champion:--- /usr/bin/scp
setfacl -m u:champion:--- /usr/local/bin/pip
setfacl -m u:champion:--- /usr/bin/nl
setfacl -m u:champion:--- /sbin/ip
setfacl -m u:champion:--- /bin/hostname
setfacl -m u:champion:--- /bin/rmdir
setfacl -m u:champion:--- /usr/bin/dpkg
setfacl -m u:champion:--- /bin/cat
setfacl -m u:champion:--- /usr/bin/setfacl
setfacl -m u:champion:--- /usr/bin/apt-get
setfacl -m u:champion:--- /usr/bin/unlink
setfacl -m u:champion:--- /bin/cp
